export const fieldMappings = {
  // Key vise Lable set
  name: "Name",
  userId: "User Name",
  email: "Email",
  phone: "Phone",
  password: "Password",
  bankName: "Bank Name",
  ifsc: "IFSC",
  isPinned: "Pinned",
  depositReqEatTime: "Average time(min)",
  minimumSuccessfulTransactionCount: "Minimum Successful Transaction",
  minimumTotalTransactionAmount: "Minimum Total Transaction Amount",
  setLimit: "Account Limit",
  accountIds: "Select Bank Account",
  accountNum: "Account Number",
  transactionPassword: "Transaction Password",
  priority: "Priority",
  isManualOrder: "Manual Order Access",
  rollBackDeposit: "Deposit Rollback",
  cryptoWalletAddress: "Wallet Address",
  isUniqueTransaction: "Unique-transaction",
  accountAllocation: "Account Selection",
  hasFullAccess: "Full Access",
  url: "URL",
  backendUrl: "Backend URL",
  tesDepositCommission: "Deposit TES Commission",
  tesWithdrawCommission: "Withdraw TES Commission",
  limitType: "Deposit Limit schedule",
  withdrawLimitType: "Withdraw Limit schedule",
  depositReqMode: "Deposit Type",
  setLimit: "Account Limit",
  cryptoWalletCoin: "Coin",
  paymentType: "Payment Type",
  apiToken: "apiToken",
  isBlock: "Is Active",
  depositAllowCount: "Deposit Allow Count",
  withdrawAllowCount: "Withdraw Allow Count",
  maxWithdrawPossible: "Max Withdraw Possible",
  type: "UTR ID Configuration Type",
  tesCommission: "PG+TES Commission",
  commission: "PG Commission",
  numberofDigits: "UTR ID Configuration Number of Digits",
  conversionToUSDT: "Conversion Rate (INR)",
  shortName: "Short Name",
  isRateAutoGenerate: "Is Rate Auto Generate",
  "settings.depositMinAmount": "Minimum Deposit Amount",
  "settings.depositMaxAmount": "Maximum Deposit Amount",
  "settings.withdrawMinAmount": "Minimum Withdraw Amount",
  "settings.withdrawMaxAmount": "Maximum Withdraw Amount",
  "settings.withdrawFlowType": "Withdraw Request Type",
  "settings.depositUpiFlowType": "Deposit Request Type",
  "depositTransactionLimit.min": "Deposit Min Limit",
  "depositTransactionLimit.max": "Deposit Max Limit",
  "withdrawTransactionLimit.min": "Withdraw Min Limit",
  "withdrawTransactionLimit.max": "Withdraw Max Limit",
  "singleTransactionLimit.min": "Minimum Amount (INR)",
  "singleTransactionLimit.max": "Maximum Amount (INR)",
  "accountPermission.bank": "Bank Permission",
  "accountPermission.upi": "UPI Permission",
  "accountPermission.crypto": "Crypto Permission",
  "settings.maxDepositTime": "Maximum Deposit Time (in Seconds)",
  "settings.maxWithdrawTime": "Maximum Withdraw Time (in Seconds)",
  "singleWithdrawTransactionLimit.min": "Minimum Amount",
  "singleWithdrawTransactionLimit.max": "Maximum Amount",
  "operatorAccess.deposit": "Deposit Permission",
  "operatorAccess.withdraw": "Withdraw Permission",
  "operatorAccess.reports": "Report Permission",
  "settings.isPaymentToWebAcc": "Web Deposit",
  "settings.isPaymentToWithWebAcc": "Web Withdraw",
  "settings.isWithdrawVerifyBalance": "Withdraw Verify Balance",
  "settings.isPgEnableForDeposit": "Payment Gateway for Deposit",
  "settings.isPgEnableForWithdraw": "Payment Gateway for Withdraw",
  "settings.requireQrForLargeDeposits": "Show QR for payments over 2000",
  "settings.redirection.depositSuccessUrl": "Deposit Success URL",
  "settings.redirection.withdrawSuccessUrl": "Withdraw Success URL",
  "settings.redirection.depositDeclineUrl": "Deposit Decline URL",
  "settings.redirection.withdrawDeclineUrl": "Withdraw Decline URL",
  "operatorAccess.deposit.read": "Deposit Permission Queue View",
  "operatorAccess.deposit.action": "Deposit Permission Queue Action",
  "operatorAccess.withdraw.read": "Withdraw Permission Queue View",
  "operatorAccess.withdraw.action": "Withdraw Permission Queue Action",
  "operatorAccess.reports.deposit": "Report Permission Deposit",
  "operatorAccess.reports.withdraw": "Report Permission Withdraw",
  "operatorAccess.reports.website": "Report Permission Website",
  "operatorAccess.reports.pg": "Report Permission PG",
  "paycials.clientId": "Client Id",
  "paycials.encryptionKey": "Encryption",
};

export const fieldValueMappings = {
  true: "On",
  false: "Off",
  random: "Random Selection",
  normal: "Account Priority",
  alphanumeric: "Alpha-Numeric",
  numeric: "Numeric",
};

// For is Block Key
export const fieldValueMappingsIsBlock = {
  true: "Off",
  false: "On",
};

export const fieldValueMappingsWithdraw = {
  tier1: "PG Request",
  tier2: "Direct Submit",
};

export const fieldValueMappingsDeposit = {
  tier1: "Verify Submit",
  tier2: "Direct Submit",
};
